// IMPORTANT: This data must stay in sync with src/data/windSiteData.ts
// Edge functions cannot import from src/ due to Deno isolation
export const windSites = [
  {
    id: 'site-1',
    name: 'North Sea - Dogger Bank Extension',
    location: 'North Sea',
    coordinates: [55.5, 2.0],
    capacityFactor: 52,
    waterDepth: 45,
    feasibility: 'excellent' as const,
    environmentalImpact: 'low' as const,
    birdMigrationRisk: 'low' as const,
    whaleMigrationRisk: 'low' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 92,
    lastAssessment: '2024-01',
    estimatedCapacity: '3,600 MW',
    country: 'UK'
  },
  {
    id: 'site-2',
    name: 'Celtic Sea - South West',
    location: 'Celtic Sea',
    coordinates: [50.0, -6.5],
    capacityFactor: 48,
    waterDepth: 75,
    feasibility: 'good' as const,
    environmentalImpact: 'medium' as const,
    birdMigrationRisk: 'medium' as const,
    whaleMigrationRisk: 'medium' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 78,
    lastAssessment: '2024-02',
    estimatedCapacity: '2,400 MW',
    country: 'UK'
  },
  {
    id: 'site-3',
    name: 'Bay of Biscay - Floating Zone',
    location: 'Bay of Biscay',
    coordinates: [44.5, -2.0],
    capacityFactor: 45,
    waterDepth: 120,
    feasibility: 'good' as const,
    environmentalImpact: 'medium' as const,
    birdMigrationRisk: 'low' as const,
    whaleMigrationRisk: 'high' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 72,
    lastAssessment: '2024-01',
    estimatedCapacity: '1,800 MW',
    country: 'France'
  },
  {
    id: 'site-4',
    name: 'Norwegian Sea - Sørlige Nordsjø II',
    location: 'Norwegian Sea',
    coordinates: [59.0, 3.5],
    capacityFactor: 55,
    waterDepth: 85,
    feasibility: 'excellent' as const,
    environmentalImpact: 'low' as const,
    birdMigrationRisk: 'low' as const,
    whaleMigrationRisk: 'low' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 95,
    lastAssessment: '2024-02',
    estimatedCapacity: '4,500 MW',
    country: 'Norway'
  },
  {
    id: 'site-5',
    name: 'Baltic Sea - Swedish Exclusive Zone',
    location: 'Baltic Sea',
    coordinates: [57.5, 19.0],
    capacityFactor: 38,
    waterDepth: 55,
    feasibility: 'moderate' as const,
    environmentalImpact: 'medium' as const,
    birdMigrationRisk: 'high' as const,
    whaleMigrationRisk: 'low' as const,
    seaFloorImpact: 'medium' as const,
    overallScore: 65,
    lastAssessment: '2023-12',
    estimatedCapacity: '1,200 MW',
    country: 'Sweden'
  },
  {
    id: 'site-6',
    name: 'Mediterranean - Gulf of Lion',
    location: 'Mediterranean',
    coordinates: [42.5, 4.0],
    capacityFactor: 40,
    waterDepth: 95,
    feasibility: 'good' as const,
    environmentalImpact: 'high' as const,
    birdMigrationRisk: 'medium' as const,
    whaleMigrationRisk: 'medium' as const,
    seaFloorImpact: 'medium' as const,
    overallScore: 58,
    lastAssessment: '2024-01',
    estimatedCapacity: '900 MW',
    country: 'France'
  },
  {
    id: 'site-7',
    name: 'Irish Sea - East Irish Coast',
    location: 'Irish Sea',
    coordinates: [53.5, -5.0],
    capacityFactor: 47,
    waterDepth: 68,
    feasibility: 'good' as const,
    environmentalImpact: 'medium' as const,
    birdMigrationRisk: 'medium' as const,
    whaleMigrationRisk: 'low' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 76,
    lastAssessment: '2024-02',
    estimatedCapacity: '2,100 MW',
    country: 'Ireland'
  },
  {
    id: 'site-8',
    name: 'German Bight - N-7.2',
    location: 'German Bight',
    coordinates: [54.5, 7.0],
    capacityFactor: 49,
    waterDepth: 42,
    feasibility: 'excellent' as const,
    environmentalImpact: 'low' as const,
    birdMigrationRisk: 'low' as const,
    whaleMigrationRisk: 'low' as const,
    seaFloorImpact: 'low' as const,
    overallScore: 88,
    lastAssessment: '2024-03',
    estimatedCapacity: '3,000 MW',
    country: 'Germany'
  }
];
