export const windSites = [
  {
    id: 'site-1',
    name: 'North Sea - Dogger Bank Extension',
    location: 'North Sea',
    description: 'One of the world\'s largest offshore wind farm projects in shallow waters of the North Sea',
    coordinates: [55.5, 2.0],
    capacityFactor: 52,
    waterDepth: 45,
    feasibility: 'excellent',
    environmentalImpact: 'low',
    birdMigrationRisk: 'low',
    whaleMigrationRisk: 'low',
    seaFloorImpact: 'low',
    overallScore: 92,
    estimatedCapacity: 3600,
    country: 'UK'
  },
  {
    id: 'site-2',
    name: 'Celtic Sea - South West',
    location: 'Celtic Sea',
    description: 'Emerging floating wind zone with high wind resources and deep waters',
    coordinates: [50.0, -6.5],
    capacityFactor: 48,
    waterDepth: 75,
    feasibility: 'good',
    environmentalImpact: 'medium',
    birdMigrationRisk: 'medium',
    whaleMigrationRisk: 'medium',
    seaFloorImpact: 'low',
    overallScore: 78,
    estimatedCapacity: 2400,
    country: 'UK'
  },
  {
    id: 'site-3',
    name: 'Bay of Biscay - Floating Zone',
    location: 'Bay of Biscay',
    description: 'Atlantic floating wind zone off the French coast with high energy potential',
    coordinates: [44.5, -2.0],
    capacityFactor: 45,
    waterDepth: 120,
    feasibility: 'good',
    environmentalImpact: 'medium',
    birdMigrationRisk: 'low',
    whaleMigrationRisk: 'high',
    seaFloorImpact: 'low',
    overallScore: 72,
    estimatedCapacity: 1800,
    country: 'France'
  },
  {
    id: 'site-4',
    name: 'Norwegian Sea - Sørlige Nordsjø II',
    location: 'Norwegian Sea',
    description: 'Deep-water floating wind opportunity with excellent wind resources',
    coordinates: [59.0, 3.5],
    capacityFactor: 55,
    waterDepth: 85,
    feasibility: 'excellent',
    environmentalImpact: 'low',
    birdMigrationRisk: 'low',
    whaleMigrationRisk: 'low',
    seaFloorImpact: 'low',
    overallScore: 95,
    estimatedCapacity: 4500,
    country: 'Norway'
  },
  {
    id: 'site-5',
    name: 'Baltic Sea - Swedish Exclusive Zone',
    location: 'Baltic Sea',
    description: 'Shallow-water fixed-bottom zone with good wind and low environmental conflict',
    coordinates: [57.5, 19.0],
    capacityFactor: 38,
    waterDepth: 55,
    feasibility: 'moderate',
    environmentalImpact: 'medium',
    birdMigrationRisk: 'high',
    whaleMigrationRisk: 'low',
    seaFloorImpact: 'medium',
    overallScore: 65,
    estimatedCapacity: 1200,
    country: 'Sweden'
  },
  {
    id: 'site-6',
    name: 'Mediterranean - Gulf of Lion',
    location: 'Mediterranean',
    description: 'Mediterranean floating wind pilot area with strong Mistral winds',
    coordinates: [42.5, 4.0],
    capacityFactor: 40,
    waterDepth: 95,
    feasibility: 'good',
    environmentalImpact: 'high',
    birdMigrationRisk: 'medium',
    whaleMigrationRisk: 'medium',
    seaFloorImpact: 'medium',
    overallScore: 58,
    estimatedCapacity: 900,
    country: 'France'
  },
  {
    id: 'site-7',
    name: 'Irish Sea - East Irish Coast',
    location: 'Irish Sea',
    description: 'Major offshore wind development area with good wind and moderate depth',
    coordinates: [53.5, -5.0],
    capacityFactor: 47,
    waterDepth: 68,
    feasibility: 'good',
    environmentalImpact: 'medium',
    birdMigrationRisk: 'medium',
    whaleMigrationRisk: 'low',
    seaFloorImpact: 'low',
    overallScore: 76,
    estimatedCapacity: 2100,
    country: 'Ireland'
  },
  {
    id: 'site-8',
    name: 'German Bight - N-7.2',
    location: 'German Bight',
    description: 'Major North Sea wind development zone with excellent feasibility',
    coordinates: [54.5, 7.0],
    capacityFactor: 49,
    waterDepth: 42,
    feasibility: 'excellent',
    environmentalImpact: 'low',
    birdMigrationRisk: 'low',
    whaleMigrationRisk: 'low',
    seaFloorImpact: 'low',
    overallScore: 88,
    estimatedCapacity: 3000,
    country: 'Germany'
  }
];
