export const windSites = [
  {
    id: "dogger-bank",
    name: "Dogger Bank",
    location: "North Sea (UK)",
    description: "One of the world's largest offshore wind farm projects in shallow waters of the North Sea",
    coordinates: [54.5, 1.8],
    capacityFactor: 52,
    waterDepth: 25,
    feasibility: "excellent",
    environmentalImpact: "medium",
    birdMigrationRisk: "medium",
    whaleMigrationRisk: "low",
    seaFloorImpact: "low",
    overallScore: 85,
    estimatedCapacity: 3600
  },
  {
    id: "hornsea",
    name: "Hornsea Zone",
    location: "North Sea (UK)",
    description: "Major offshore wind development area off the Yorkshire coast",
    coordinates: [53.9, 1.8],
    capacityFactor: 48,
    waterDepth: 32,
    feasibility: "excellent",
    environmentalImpact: "medium",
    birdMigrationRisk: "high",
    whaleMigrationRisk: "low",
    seaFloorImpact: "medium",
    overallScore: 82,
    estimatedCapacity: 2400
  },
  {
    id: "hywind-scotland",
    name: "Hywind Scotland",
    location: "North Sea (Scotland)",
    description: "World's first floating wind farm demonstrating deep-water technology",
    coordinates: [57.5, -1.3],
    capacityFactor: 54,
    waterDepth: 95,
    feasibility: "good",
    environmentalImpact: "low",
    birdMigrationRisk: "low",
    whaleMigrationRisk: "medium",
    seaFloorImpact: "low",
    overallScore: 88,
    estimatedCapacity: 30
  },
  {
    id: "celtic-sea",
    name: "Celtic Sea Floating",
    location: "Celtic Sea (UK)",
    description: "Emerging floating wind zone with high wind resources and deep waters",
    coordinates: [50.5, -6.5],
    capacityFactor: 56,
    waterDepth: 85,
    feasibility: "good",
    environmentalImpact: "low",
    birdMigrationRisk: "low",
    whaleMigrationRisk: "medium",
    seaFloorImpact: "low",
    overallScore: 90,
    estimatedCapacity: 4000
  },
  {
    id: "gulf-of-lion",
    name: "Gulf of Lion",
    location: "Mediterranean (France)",
    description: "Mediterranean floating wind pilot area with strong Mistral winds",
    coordinates: [43.0, 4.5],
    capacityFactor: 45,
    waterDepth: 120,
    feasibility: "moderate",
    environmentalImpact: "medium",
    birdMigrationRisk: "medium",
    whaleMigrationRisk: "medium",
    seaFloorImpact: "low",
    overallScore: 75,
    estimatedCapacity: 250
  },
  {
    id: "bay-of-biscay",
    name: "Bay of Biscay",
    location: "Atlantic (France)",
    description: "Atlantic floating wind zone off the French coast with high energy potential",
    coordinates: [45.5, -2.5],
    capacityFactor: 51,
    waterDepth: 100,
    feasibility: "good",
    environmentalImpact: "medium",
    birdMigrationRisk: "medium",
    whaleMigrationRisk: "high",
    seaFloorImpact: "low",
    overallScore: 78,
    estimatedCapacity: 1500
  },
  {
    id: "norwegian-sea",
    name: "Norwegian Sea",
    location: "Norwegian Sea (Norway)",
    description: "Deep-water floating wind opportunity with excellent wind resources",
    coordinates: [64.5, 5.5],
    capacityFactor: 58,
    waterDepth: 250,
    feasibility: "challenging",
    environmentalImpact: "low",
    birdMigrationRisk: "low",
    whaleMigrationRisk: "medium",
    seaFloorImpact: "low",
    overallScore: 80,
    estimatedCapacity: 3000
  },
  {
    id: "baltic-sea",
    name: "Baltic Sea Wind Zone",
    location: "Baltic Sea (Sweden)",
    description: "Shallow-water fixed-bottom zone with good wind and low environmental conflict",
    coordinates: [58.5, 18.5],
    capacityFactor: 42,
    waterDepth: 28,
    feasibility: "excellent",
    environmentalImpact: "low",
    birdMigrationRisk: "low",
    whaleMigrationRisk: "low",
    seaFloorImpact: "low",
    overallScore: 86,
    estimatedCapacity: 1200
  }
];
